### ISSUE TITLE
[BUG] MATT Tile References break

### ISSUE THREAD

**Issue by TiltedWatcher** [League-of-Foundry-Developers/scene-packer#123]
**Describe the bug**
When importing a scene that makes use of Monks Active Tile Triggers, the references to other entities break.

More specifically, in the action flow on a tile, any actions that reference another entity in the scene via it's ID, just reference nothing, breaking anything set up to work via MATT. That's despite the referenced entity in question retaining it's ID.

For example if a tile is set up to open a set of doors on double click, the doors are referenced in the tile, by their ID. Once the scene is imported in Foundry, the reference is empty.

Essentially that means to fix the problem all references have to manually be re-entered, which defeats the purpose of using Scene packer to seamlessly import a scene and have it ready to be used immediately.

**Versions (please complete the following information):**
 - FoundryVTT Core: 10.291
- System: dnd5e 2.1.5  
- scene-packer 2.6.16 
- monks-active-tiles 10.19

**To Reproduce**
1. Set up a Scene using MATT. 
2. Make sure to have the action flow in one tile, reference another entity in the scene (for example, set up a tile to act as a switch that opens a door, and changes the visibility of another tile, when double clicked.)
3. Pack/Export the scene as described in the Documentation for Scene Packer
4. Activate the module containing the scene in a different world
5. Import the scene
6. The IDs of entities are the same, but the references are now broken.

**Expected behavior**
The tiles set up in MATT would work without requiring any additional setup, Using the above example, double clicking the tile should open the door and change the visibility of the other tile.
Within the tile configuration, the actions set up, should still contain references to the other tiles/walls/etc

**Screenshots**
The configuration in the original scene.
![image](https://github.com/League-of-Foundry-Developers/scene-packer/assets/78517803/3a8ab2a6-10f5-4f23-82c1-d60dcd613564)

What it looks like once the scene is imported into a different world. Note that the other tile still has the same ID (kjEqRdgVfZN2QsMS in this instance), but the reference itself is empty.
![image](https://github.com/League-of-Foundry-Developers/scene-packer/assets/78517803/ef8eb134-3ff6-4cba-bdd8-cf9569d1fc9a)
The bottom half of this screenshot is irrelevant, just had the tile configuration for the referenced tile open to show that the ID is the same.

**Comment by sneat** [comment]
Thanks for the detailed report @TiltedWatcher 

I'll take a look, Ironmonk sometimes refactors the way that MATT stores its data, so I wonder whether that's happened again.

**Comment by sneat** [comment]
I haven't been able to replicate this @TiltedWatcher - are you able to join my [discord](https://discord.com/invite/HY3xhBEf2A) and we can organise some additional debugging?

**Comment by TiltedWatcher** [comment]
Sure, can do.

Will have to wait a few hours until I'm home though.

**Comment by sneat** [comment]
@TiltedWatcher are you happy to close this issue now after our discussions?

**Comment by TiltedWatcher** [comment]
Oh, absolutely, completely forgot about still having it open, my bad

**Comment by sneat** [comment]
If anyone comes across this in the future, this specific issue was related to changing the name of the module after packing the scenes.
