### ISSUE TITLE
[FEATURE] Support default playlist on scene activation

### ISSUE THREAD

**Issue by timartiny** [League-of-Foundry-Developers/scene-packer#14]
**Is your feature request related to a problem? Please describe.**
When creating an adventure module, the default playlist is forgotten on importing a scene if the playlist is only saved in a compendium. Scene packer solves this for journals, but not playlists.

**Describe the solution you'd like**
I'd like an extension of Scene packer to preserve the default playlist when importing a scene, if the playlist has been imported from a compendium.

**Describe alternatives you've considered**
Alternative solutions are to just put "notes" in the journal entries for each scene of how to reconstruct--not a Scene Packer feature.

**Comment by sneat** [comment]
@timartiny feature added in [v2.1.1](https://github.com/League-of-Foundry-Developers/scene-packer/releases/tag/2.1.1)

You will need to re-export your playlists to your compendium for the linking to work correctly.
