### ISSUE TITLE
[BUG] Can't relink compendium entries with markdown format

### ISSUE THREAD

**Issue by DaGwann** [League-of-Foundry-Developers/scene-packer#147]
## **Describe the bug**
There's a feature in Foundry where a journal entry page edited via markdown format can't be edited and saved with the default text editor any more, only as markdown. This makes the relink tool from Scene Packer uncapable of relinking the compendium entries from a markdown journal page.

**Versions (please complete the following information):**
 - FoundryVTT Core: 12.331
 - System: DnD5e 4.0.4
 - Scene Packer Version 2.7.15

### Making a journal entry only editable as Markdown:
1. Create a new Journal
2. Add a page to the journal, immediately switch to the markdown editor
3. Add some text and save
4. Edit and change some text in the markdown editor, save
5. See that the changes have been applied
6. Edit again and switch to the default text editor, make a change and save
7. See that the changes have not been applied. This journal page is now only editable as markdown.

### Exporting journal entries with markdown pages and trying to relink compendium entries:
1. Create journal entries, add pages to them and edit them using markdown format as previously described, adding links in them to other journal entries.
2. See that the journal entries have the links visible and functional.
3. Export the journals to the Scene Packer compendium
4. See that the same behaviour as described before still applies in the compendium journal entries (only edits done in markdown format are saved)
5. Use the relink tool from Scene Packer's macro.
6. See that no links have been edited, still retaining the original links to the journal entries, instead of the compendium entries.

**Expected behavior**
I don't know what can be done to solve this situation, but the expected behaviour would be that Scene Packer is able to edit journal pages that have been created and are only editable via markdown.

## **Screenshots**
Video showing two journal entries, one with markdown page and other with normal page. The journals are exported to the Scene Packer compendium, keeping the same format. The relink tool is used, and it can be seen how the normal journal page has been correctly relinked, while the markdown journal page keeps its original links.

https://github.com/user-attachments/assets/e1b8b420-cc81-47d8-9298-6500f1a5c1e6

## **Additional context**
The use case of markdown journal pages, for me, has to do with the use of another module, Lava Flow. I use the software Obsidian MD to create and manage my worldbuilding and GM, generating .md files. With Lava Flow, those files can conveniently be imported into Foundry, and the links between notes created in Obsidian are converted to journal links using Foundry formulas. But, as Obsidian works with markdown, I understand that Lava Flow uses this format too, to create the journal entries.

I want to export these entries into compendiums and remove the original journal entries. This way, I'll have my worldbuilding notes available inside Foundry for my players to consult, in the Compendium section. Having them in a compendium is preferable, as it eases loading times.

But as explained, this method loses it's appeal once the links between entries can't be preserved, because the original journal entries will be deleted, and Scene Packer can't edit the markdown journal pages.

**Comment by sneat** [comment]
Thank you for the detailed report @DaGwann 

I had thought that editing one format would edit the other, but that's clearly not the case. I'll work on a fix for it.

**Comment by sneat** [comment]
I believe I have fixed this up @DaGwann - it's in the `2.8.0` branch if you are familiar with downloading off github and would like to test it early.
