### ISSUE TITLE
Make it clear there are cascading dependancies.

### ISSUE THREAD

**Issue by BillPitcher** [League-of-Foundry-Developers/scene-packer#45]
I'm always frustrated when I install a module and it then prompts to install another module... I'm left unsure as to just delete this and find another option or keep add more thing to the house of cards...

Make it clear in the description and other documentaion there are dependancies and what may/may not happen if I chose not to add them.

**Describe alternatives you've considered**
An alternative is to make your module standalone. It's all ready a problem that I'm making my module dependant on your module, which is also dependant on that module. What if I find that module is dependant on some other module...
![Screen Shot 2021-06-20 at 3 17 45 pm](https://user-images.githubusercontent.com/4987108/122663170-d5cda800-d1db-11eb-9785-09233d62f60e.png)

**Comment by sneat** [comment]
Hi @BillPitcher 

Sorry for the frustration. I don’t make it a hard dependency because it isn’t one. The subset of libWrapper is included in Scene Packer that gives the core functionality of warning if there are conflicts with some of the aspects of Foundry VTT that Scene Packer wraps. 

Choosing “Don’t remind me again” shouldn’t give you any troubles but also won’t give you the best compatibility with other modules. 

What solution would you suggest?

**Comment by BillPitcher** [comment]
Hi Blair,

I have been thinking on this. Asking the end user what they want is good. 

As the content developer, I would ask my end user what they want? What they want/need is to put in my content URL, and click install. Load their world...  (and enable the module I feel this step should not be necessary, but that’s not our problem).

Then open the scene Compendium and drag a scene into the list of scenes and Activate. And it’s ready to run the game.

Now, how can we achieve this with no friction? That is the challenge.

For me as a content creator, (I’m happy to leave the coding to the next generation) the best solution would be to download a Script and a folder of yours to drop in my module folder
Add the Script to my module.js.
The only thing I have to write is a .json file with all the other information your script needs next to it.

As the DM using the content, no cascading installations, not from me, not from you.

Let me make clear I think you and all the developers working on Foundry are fantastic. It is the reason I’m making content for Foundry. Why this functionality isn’t built in I don’t know.

In the mean time I’ll fork my project, 1 with no dependancies, 1 with. I’ll keep looking for a script that relinks the Map Tokens to their Sheets somehow.

cheers
@BillPitcher

**Comment by sneat** [comment]
Thanks for the additional context and information @BillPitcher 

I’ll have a think on options this morning. Are you on discord at all? Maybe we can chat a little more through the options?

**Comment by sneat** [comment]
Have requested some clarification in https://github.com/ruipin/fvtt-lib-wrapper/issues/43 to help determine exactly what functionality would be lost if an end user doesn't use the full version of libWrapper.

**Comment by sneat** [comment]
I have adjusted how this displays now in [v2.2.25](https://github.com/League-of-Foundry-Developers/scene-packer/releases/tag/2.2.25). Let me know what you think @BillPitcher.
