### ISSUE TITLE
[BUG] Conflict with Warhammer Module

### ISSUE THREAD

**Issue by Craftzero** [League-of-Foundry-Developers/scene-packer#78]
**Describe the bug**
Receive an error upon entering Warhammer via the Libwrapper module.  In practice, I have seen some oddities tied to Baileywiki modules that may have Scene Packer requirements.

**Versions (please complete the following information):**
 - FoundryVTT Core: Version 9 - Build 238
 - System: Warhammer v5.0.3
 - Scene Packer Version: v2.3.25

**To Reproduce**
1. Install Warhammer/Lib Wrapper/Scene Packer
2. Start Up Warhammer

**Expected behavior**
I would expect no error upon starting Warhammer.

**Screenshots**
<img width="420" alt="Capture2" src="https://user-images.githubusercontent.com/92058223/147411053-0fe80f09-2526-444d-b33f-5231d3289a88.PNG">

<img width="716" alt="Capture1" src="https://user-images.githubusercontent.com/92058223/147411069-001c35e9-f170-445a-bb92-e821d4da5618.PNG">

**Additional context**

**Comment by sneat** [comment]
Hi @Craftzero, as discussed on Discord, this technically isn't an error, it's a warning. It's annoying getting warnings like this in the console, but it shouldn't be causing any problems for you for the following reasons:

1. The potential conflict only exists when exporting Journals, Scenes or RollTables to a compendium, which I assume you aren't doing very often (if at all).
2. The way that Scene Packer has wrapped that portion, it should be calling the Warhammer version of the `toCompendium` methods, and then adding its additional data. So there shouldn't be an issue.

I'll leave this issue open for now though while we discuss more on Discord just in case there's something that I can adjust in Scene Packer to make the interaction better overall.

**Comment by sneat** [comment]
Other issue mentioned on Discord was resolved within the Warhammer system.
