### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by schlosrat** [League-of-Foundry-Developers/scene-packer#81]
**Describe the bug**
Not really a bug, but FYI you're using a deprecated approach to checking the game version in 48 places within scene-packer.js, 13 places in asset-report.js, 2 places in report.js, 1 place in wrapped.js, and 3 places in module-select.js. This is causing warning messages in the console when users include your module and launch their world.

**Versions (please complete the following information):**
 - FoundryVTT Core: [e.g. 0.9.242]
 - System [e.g. age-system 10.2]
 - Scene Packer Version [e.g. 2.3.27]

**To Reproduce**
1. include module
2. launch/relaunch world
2. go to console and see the warning
game.data.version is deprecated in V9 in favor of game.version

**Expected behavior**
It would be nice to not see the warning

**Screenshots**

**Additional context**

**Comment by sneat** [comment]
Thanks for the report @schlosrat 

Those changes have been done in the v2.4.0 branch. You can find the alpha release for it on the releases page, otherwise stick tight for the public release 👍

**Comment by sneat** [comment]
Closing now that v2.4.0 has been released.
