### ISSUE TITLE
[BUG] Error encountered during "Bulk replace asset references" macro.

### ISSUE THREAD

**Issue by mattmeng** [League-of-Foundry-Developers/scene-packer#88]
Thank you for making this excellent module.  Please let me know any way I can be more helpful.

**Describe the bug**
When running the macro "Bulk replace asset references", I get the following error:

![image](https://user-images.githubusercontent.com/184780/156064584-76572444-1e89-493d-afc0-dade97bd5683.png)

This kills execution of the rest of the script.

**Versions (please complete the following information):**
 - FoundryVTT Core: 9.245
 - System: DnD5e 1.5.7
 - Scene Packer Version: 2.4.0

**To Reproduce**
I'm sure it has something to do with my particular setup.

1. Open the console.
2. Run the "Bulk replace asset references" macro.
3. Input the following into "Find": `upload/journal-icon-numbers`
4. Input the following into "Replace": `modules/curse-of-strahd/assets/journal-icon-numbers`
5. Click "Bulk replace".
6. See error in console.

**Expected behavior**
The macro to replace correctly and without error.

**Comment by mattmeng** [comment]
In messing around with it, I've gotten past the error by editing the macro and moving the offending variable's declaration out of the loop it is in.  I would submit a pull request, but I'm not sure how to edit the macro within the repository.  Any help you could provide would be appreciated and I can generate a pull request for you.

**Comment by sneat** [comment]
Thanks for the report @mattmeng I'll fix it up in the next release (v2.4.1).

**Comment by mattmeng** [comment]
Thank you.  Even after the fix, I'm still encountering an issue bulk replacing `upload/journal-icon-numbers`.  It's like it isn't finding it in any of my journal entries.  I am using [Monk's Enhanced Journal](https://github.com/ironmonk88/monks-enhanced-journal) and [Automatic Journal Icon Numbers](https://gitlab.com/tiwato/journal_icon_numbers) and I'm wondering if something is getting in the way of it finding references for those entries.

Is there a support paradigm you would prefer this in, or is the bug the appropriate place?  Thanks for any help you can provide.

**Comment by mattmeng** [comment]
For context, this is what I'm seeing on my asset report:

![image](https://user-images.githubusercontent.com/184780/156075219-c9a056dd-f996-49cd-844a-d05a6f884369.png)

When I bulk replace, these references get missed:

![image](https://user-images.githubusercontent.com/184780/156075284-03b88050-9e45-435b-902f-33ab1c0217d2.png)

![image](https://user-images.githubusercontent.com/184780/156075312-3a507115-f526-47ac-a73a-8e3968413044.png)

**Comment by mattmeng** [comment]
After playing around, I found that the bulk edit script wasn't taking into account scene notes.  I added the following to my own script in the "Bulk replace scenes" loop right under the "Tile update" section:

```js
        const noteUpdates = [];
        shownGroup = false;
        for (const note of scene.notes) {
          if (note.data.icon?.startsWith(find)) {
            if (!shownGroup) {
              console.groupCollapsed(`${scene.name} notes`);
              shownGroup = true;
            }
            console.log(
              `note.icon: ${note.data.icon} => ${note.data.icon.replace(
                find,
                replace
              )}`
            );
            noteUpdates.push({
              _id: note.id,
              icon: note.data.icon.replace(find, replace),
            });
          }
        }
        if (shownGroup) {
          console.groupEnd();
        }
        if (noteUpdates.length && !dryRun) {
          await scene.updateEmbeddedDocuments("Note", noteUpdates);
        }
```

**Comment by sneat** [comment]
That's perfect @mattmeng well done.

This is a fine place to raise issues, there's also the Discord server linked at the bottom of the readme if you'd like too.

I wonder if you had an older version of the bulk replace macro too, because I don't get the original error in v2.4.0 and I remember fixing that bug in the past.

**Comment by mattmeng** [comment]
Might be, I don't remember reimporting the macro lately, I'll check that to make sure.  Another tip for anyone else that encounters this issue, the Automatic Journal Icon Numbers module automatically builds after it detects that you move the journal icon images folder.  I got around that by changing the setting to point to my new folder before making the migration.

![image](https://user-images.githubusercontent.com/184780/156081159-98e1b90b-e7e5-45ae-8a1a-0297ca295032.png)

I'll leave you to close this, @sneat; I'm not sure on your issue management preferences.  Everything looks fine on my end.  Thank you again for your excellent work on this module.  To me, this is just incredibly useful.

**Comment by sneat** [comment]
@mattmeng there's a config setting for Automatic Journal Icon Numbers that you can set to not automatically create the icons as well. The setting you've changed is probably the better one overall, but this is more for completeness to anyone else looking at this issue in the future.

I'll leave this ticket open until I release 2.4.1 with your update for the icons.
