### ISSUE TITLE
Import fails to assign "Encounter" to Monk's Enhanced Journal Entities

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [League-of-Foundry-Developers/scene-packer#89]
**Submitted By**: cj.powers121@gmail.com
**Feedback Type**: Enhancement
 
**Core:** 9.242
**System:** dnd5e v1.5.7
**Module Version:** scene-packer v2.3.29
 
**Description**:
When creating a scenepacker enabled module, and exporting a series of journal entries that are "encounters" per Monk's Enhanced Journal, following import into a new world, the journal entries are no longer encounters, any monsters assigned to them are no longer present, and the encounter no longer functions properly.<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>

bug-reporter--v1.3.3;
cos-random-encounters-drodinn--v1.0.0;
lib-wrapper--v1.12.4.0;
monks-enhanced-journal--v1.0.45;
scene-packer--v2.3.29;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by sneat** [comment]
This has been resolved in version 1.0.50 of Monk's Enhanced Journal https://github.com/ironmonk88/monks-enhanced-journal/blob/main/CHANGELOG.md#version-1050
